version: '3'
services:
  invillia-database:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - 'database.env'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  invillia-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 2080:80
    env_file:
      - 'database.env'
